### ISSUE TITLE
Proper translations storage

### ISSUE THREAD

**Issue by Rorkh** [mxkmn/OWM_for_ESP#5]
Current way to store translations phrases is really uncomfortable to modify as I see. I think it is will be better to store translation phrases in header file like this
```cpp
namespace translation 
{
#ifdef RU
inline constexpr std::string something = "Что-то";
#elifdef EN
inline constexpr std::string something = "Something";
#endif
}
```

As I see it, it should mke maintaining, acessing and modification of translation phrases more easy. Of course also translation phrases can be splitted into each file for each language but I don't think it is really needed here.

**Comment by mxkmn** [comment]
I'm sorry, but I don't see how modifying translations will be easier.

Right now, all translations are stored at the end of a shared file and are built on a primitive `switch` and `if` operator. This is convenient because for a lot of translations in `getShortStatus()` and `getStatus16()` methods, the translations are similar but slightly different and the arguments can easily be adjusted to a specific language. 
For example, when in English `getShortStatus()` codes 731 and 751 correspond to "Dust" and "Sand", in Russian these codes correspond to one translation: "Sand", so there used `if` with two operators `==`.
This allows you not to duplicate the same words for different statuses. Similarly, in `getStatus16()` the use of `switch` allows you to avoid duplication of short statuses thanks to `default: return(getStatus(id));`.

If you'll have to translate your code completely to the construct you've suggested, I don't know how to make such optimizations, which will be optimal for every language. It's easier to modify the initial code and doesn't require the knowledge of rare constructs like `inline constexpr std::string something = "Something";` by beginners.

If you can offer a real case of code improvement without adding repeats and, preferably, with a full-fledged code example, I will certainly look into it and make a decision.
